In [1]:
# 데이터가져오기

import pandas as pd

path = '../bicycle/bicycle_dup.csv'


df = pd.read_csv(path, encoding='cp949')

In [2]:
df

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리,나이
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 9:01,3,중랑센터,7.0,12.0,1100.0,50
1,SPB-16216,2019-11-04 8:38,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-04 8:56,3,중랑센터,2.0,7.0,1100.0,50
2,SPB-21097,2019-11-04 8:46,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-04 8:57,3,중랑센터,7.0,10.0,NaN,32
3,SPB-22292,2019-11-05 8:34,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-05 8:45,3,중랑센터,NaN,10.0,1380.0,21
4,SPB-07935,2019-11-05 12:29,512,뚝섬역 1번 출구 옆,11.0,2019-11-05 12:39,3,중랑센터,7.0,10.0,1650.0,120
...,...,...,...,...,...,...,...,...,...,...,...,...
415,SPB-12116,2019-11-15 4:22,112,극동방송국 앞,5.0,2019-11-15 4:33,101,(구)합정동 주민센터,1.0,11.0,2200.0,22
416,SPB-17768,2019-11-15 9:31,103,망원역 2번출구 앞,14.0,2019-11-15 9:37,101,(구)합정동 주민센터,NaN,5.0,NaN,22
417,SPB-18841,2019-11-15 20:40,113,홍대입구역 2번출구 앞,24.0,2019-11-15 20:53,101,(구)합정동 주민센터,1.0,12.0,2280.0,37
418,SPB-24467,2019-11-15 21:55,152,마포구민체육센터 앞,18.0,2019-11-15 22:05,101,(구)합정동 주민센터,1.0,10.0,1180.0,27
419,SPB-17570,2019-11-15 22:16,391,정동길입구,7.0,2019-11-15 23:04,101,(구)합정동 주민센터,5.0,48.0,8100.0,28

In [3]:
df.describe()

,대여소번호,대여거치대,반납대여소번호,반납거치대,이용시간,이용거리,나이
count,420.000000,396.000000,420.000000,409.000000,405.000000,404.000000,420.000000
mean,243.254762,7.585859,93.338095,2.843521,21.185185,2683.465347,35.492857
std,301.148255,6.258985,26.270667,1.699182,20.200058,3025.803402,31.829010
min,3.000000,1.000000,3.000000,1.000000,2.000000,0.000000,21.000000
25%,104.000000,3.000000,101.000000,1.000000,7.000000,1070.000000,24.000000
50%,117.500000,6.000000,101.000000,2.000000,14.000000,1680.000000,29.000000
75%,226.500000,10.000000,101.000000,4.000000,27.000000,3757.500000,40.000000
max,3102.000000,30.000000,101.000000,7.000000,122.000000,42070.000000,533.000000

In [7]:
df[df['이용거리'].isnull()]

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리,나이
2,SPB-21097,2019-11-04 8:46,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-04 8:57,3,중랑센터,7.0,10.0,NaN,32
12,SPB-19057,2019-11-13 8:55,646,장한평역 1번출구 (국민은행앞),4.0,2019-11-13 9:08,3,중랑센터,7.0,11.0,NaN,57
23,SPB-19256,2019-11-26 10:20,3,중랑센터,7.0,2019-11-26 10:24,3,중랑센터,NaN,3.0,NaN,29
37,SPB-14246,2019-11-01 2:21,120,신수동 사거리,5.0,2019-11-01 2:45,101,(구)합정동 주민센터,2.0,23.0,NaN,46
70,SPB-08265,2019-11-02 14:24,104,합정역 1번출구 앞,2.0,2019-11-02 14:53,101,(구)합정동 주민센터,1.0,28.0,NaN,28
94,SPB-11003,2019-11-02 23:45,102,망원역 1번출구 앞,9.0,2019-11-02 23:52,101,(구)합정동 주민센터,2.0,6.0,NaN,21
128,SPB-03349,2019-11-03 23:03,124,서강대 정문 건너편,5.0,2019-11-03 23:23,101,(구)합정동 주민센터,3.0,19.0,NaN,40
179,SPB-14571,2019-11-05 9:09,438,성산2-1 공영주차장,2.0,2019-11-05 9:27,101,(구)합정동 주민센터,5.0,17.0,NaN,37
252,SPB-07514,2019-11-07 18:59,225,앙카라공원 앞,2.0,2019-11-07 19:29,101,(구)합정동 주민센터,5.0,29.0,NaN,24
264,SPB-20868,2019-11-08 9:46,104,합정역 1번출구 앞,8.0,2019-11-08 9:54,101,(구)합정동 주민센터,4.0,7.0,NaN,35
279,SPB-14276,2019-11-08 19:07,410,상암중학교 옆,4.0,2019-11-08 19:33,101,(구)합정동 주민센터,4.0,25.0,NaN,22
295,SPB-16380,2019-11-09 0:35,419,홈플러스 앞,20.0,2019-11-09 0:51,101,(구)합정동 주민센터,1.0,16.0,NaN,28
315,SPB-24164,2019-11-10 10:04,182,망원2빗물펌프장 앞,4.0,2019-11-10 10:40,101,(구)합정동 주민센터,2.0,35.0,NaN,26
372,SPB-06102,2019-11-12 18:55,151,망원1동주민센터,9.0,2019-11-12 19:02,101,(구)합정동 주민센터,2.0,6.0,NaN,21
409,SPB-10593,2019-11-14 23:29,106,합정역 7번출구 앞,5.0,2019-11-14 23:40,101,(구)합정동 주민센터,4.0,10.0,NaN,28
416,SPB-17768,2019-11-15 9:31,103,망원역 2번출구 앞,14.0,2019-11-15 9:37,101,(구)합정동 주민센터,NaN,5.0,NaN,22

In [8]:
df[df['이용거리']==2290]

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리,나이
98,SPB-11651,2019-11-02 23:54,228,선유도역 3번출구 앞,8.0,2019-11-03 0:09,101,(구)합정동 주민센터,3.0,15.0,2290.0,23
400,SPB-15391,2019-11-14 17:14,113,홍대입구역 2번출구 앞,22.0,2019-11-14 17:29,101,(구)합정동 주민센터,1.0,NaN,2290.0,31

In [10]:
df_group = df.groupby('이용거리')
df_group.mean()

               대여소번호     대여거치대  반납대여소번호     반납거치대   이용시간          나이
이용거리
0.0       130.583333  8.583333    101.0  2.272727   15.8   29.416667
20.0      101.000000  2.000000    101.0  3.000000    2.0   48.000000
280.0     260.000000  2.000000     53.0  3.500000    4.0  278.000000
440.0     106.000000  2.000000    101.0  1.000000   12.0   57.000000
450.0     262.500000  8.000000     53.0  4.000000   23.5   32.500000
...              ...       ...      ...       ...    ...         ...
10260.0  1160.000000  1.000000    101.0  1.000000   47.0   25.000000
12610.0  1925.000000  6.000000    101.0  4.000000   62.0   66.000000
16910.0  2103.000000  1.000000    101.0  1.000000  121.0   46.000000
17060.0  2103.000000  3.000000    101.0  4.000000  121.0   24.000000
42070.0   116.000000  3.000000    101.0  4.000000   46.0   22.000000

[256 rows x 6 columns]

In [13]:
print(df_group.mean().loc[2290])

대여소번호      170.5
대여거치대       15.0
반납대여소번호    101.0
반납거치대        2.0
이용시간        15.0
나이          27.0
Name: 2290.0, dtype: float64

In [14]:
df_group.mean().loc[2290]['이용시간']

15.0

In [17]:
print(df['이용거리'][:5])
print(df.duplicated(['이용거리'])[:5])

0    1100.0
1    1100.0
2       NaN
3    1380.0
4    1650.0
Name: 이용거리, dtype: float64
0    False
1     True
2    False
3    False
4    False
dtype: bool

In [20]:
print(df)

         자전거번호              대여일시  대여소번호               대여소명  대여거치대  \
0    SPB-23220   2019-11-01 8:48    646  장한평역 1번출구 (국민은행앞)    3.0
1    SPB-16216   2019-11-04 8:38    646  장한평역 1번출구 (국민은행앞)    2.0
2    SPB-21097   2019-11-04 8:46    646  장한평역 1번출구 (국민은행앞)    1.0
3    SPB-22292   2019-11-05 8:34    646  장한평역 1번출구 (국민은행앞)    1.0
4    SPB-07935  2019-11-05 12:29    512        뚝섬역 1번 출구 옆   11.0
..         ...               ...    ...                ...    ...
415  SPB-12116   2019-11-15 4:22    112            극동방송국 앞    5.0
416  SPB-17768   2019-11-15 9:31    103         망원역 2번출구 앞   14.0
417  SPB-18841  2019-11-15 20:40    113       홍대입구역 2번출구 앞   24.0
418  SPB-24467  2019-11-15 21:55    152         마포구민체육센터 앞   18.0
419  SPB-17570  2019-11-15 22:16    391              정동길입구    7.0

                 반납일시  반납대여소번호       반납대여소명  반납거치대  이용시간    이용거리   나이
0     2019-11-01 9:01        3         중랑센터    7.0  12.0  1100.0   50
1     2019-11-04 8:56        3         중랑센터    2.0   7.0  1100.0   50
2     2019-11-04 8:57        3         중랑센터    7.0  10.0     NaN   32
3     2019-11-05 8:45        3         중랑센터    NaN  10.0  1380.0   21
4    2019-11-05 12:39        3         중랑센터    7.0  10.0  1650.0  120
..                ...      ...          ...    ...   ...     ...  ...
415   2019-11-15 4:33      101  (구)합정동 주민센터    1.0  11.0  2200.0   22
416   2019-11-15 9:37      101  (구)합정동 주민센터    NaN   5.0     NaN   22
417  2019-11-15 20:53      101  (구)합정동 주민센터    1.0  12.0  2280.0   37
418  2019-11-15 22:05      101  (구)합정동 주민센터    1.0  10.0  1180.0   27
419  2019-11-15 23:04      101  (구)합정동 주민센터    5.0  48.0  8100.0   28

[420 rows x 12 columns]

In [21]:
print(df.duplicated(['이용거리']))

0      False
1       True
2      False
3      False
4      False
       ...
415    False
416     True
417     True
418     True
419    False
Length: 420, dtype: bool

In [22]:
df.duplicated(['이용거리','나이'])

0      False
1       True
2      False
3      False
4      False
       ...
415    False
416     True
417    False
418    False
419    False
Length: 420, dtype: bool

In [23]:
df.duplicated(['이용거리'], keep='last')

0       True
1       True
2       True
3       True
4      False
       ...
415    False
416    False
417    False
418    False
419    False
Length: 420, dtype: bool