In [3]:
import pandas as pd

path = '../data/Seoul_school/Seoul_school.csv'

df = pd.read_csv(path, encoding='cp949')

df

,학교종류명,설립구분,표준학교코드,학교명,영문학교명,관할조직명,도로명우편번호,도로명주소,도로명상세주소,전화번호,...,주야구분명,설립일자,개교기념일,시도교육청코드,시도교육청명,소재지명,주야과정,계열명,학과명,적재일시
0,각종학교(중),사립,7134155,선화예술중학교,Sunhwa Arts Middle School,서울특별시성동광진교육지원청,4991.0,서울특별시 광진구 천호대로 664,/ 선화예술중고등학교 (능동),02-2204-1100,...,주간,19731201,19730705,B10,서울특별시교육청,서울특별시,NaN,NaN,NaN,20210602
1,초등학교,공립,7134150,서울숭신초등학교,Seoul Soongshin Elementary School,서울특별시성동광진교육지원청,4702.0,서울특별시 성동구 마장로 161,(하왕십리동),02-2252-5950,...,주간,19590403,19590403,B10,서울특별시교육청,서울특별시,NaN,NaN,NaN,20210602
2,중학교,공립,7134142,행당중학교,Haengdang Middle School,서울특별시성동광진교육지원청,4764.0,서울특별시 성동구 왕십리로 189,(행당동/행당중학교),02-2292-2721,...,주간,19680806,19681002,B10,서울특별시교육청,서울특별시,NaN,NaN,NaN,20210602
3,중학교,사립,7134141,한양대학교사범대학부속중학교,Hanyang University Middle School,서울특별시성동광진교육지원청,4761.0,서울특별시 성동구 마조로 42,(사근동/한양사대부속중?고등학교),02-2200-3700,...,주간,19600118,19600118,B10,서울특별시교육청,서울특별시,NaN,NaN,NaN,20210602
4,중학교,공립,7134140,자양중학교,Jayang Middle School,서울특별시성동광진교육지원청,5069.0,서울특별시 광진구 뚝섬로41길 33,(자양동/서울자양중학교),02-446-0365,...,주간,19840301,19840301,B10,서울특별시교육청,서울특별시,NaN,NaN,NaN,20210602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3852,고등학교,국립,1371661,국립국악고등학교,Gukak National High School,교육부,6311.0,서울특별시 강남구 개포로22길 65,/ (개포동/ 국립국악고등학교),02-3460-0500,...,주간,19720711,19720909,B10,서울특별시교육청,서울특별시,주간,예술계,무용과,20210602
3853,특수학교,국립,1342102,한국우진학교,Hanguk Woojin School,교육부,3934.0,서울특별시 마포구 월드컵북로38길 21,/ 한국우진학교 (중동),02-6388-5800,...,주간,20000301,20000306,B10,서울특별시교육청,서울특별시,NaN,NaN,NaN,20210602
3854,특수학교,국립,1342099,서울농학교,Seoul National school for the Deaf,교육부,3032.0,서울특별시 종로구 필운대로 103,(신교동),02-737-0659,...,주간,19130401,19130401,B10,서울특별시교육청,서울특별시,NaN,NaN,NaN,20210602
3855,특수학교,국립,1342098,서울맹학교,Seoul National School for the Blind,교육부,3032.0,서울특별시 종로구 필운대로 97,(신교동),02-731-6772,...,주간,19130401,19130401,B10,서울특별시교육청,서울특별시,NaN,NaN,NaN,20210602
3856,공동실습소,공립,0,경기기계공업고등학교부설공동실습소,NaN,서울특별시교육청,139869.0,서울특별시 노원구 공릉로 264,(하계동/경기기계공업고등학교),02-970-8922,...,주간,19820601,19820601,B10,서울특별시교육청,서울특별시,주간,기계공동실습소,공동실습소,20210602

In [4]:
for col in df.columns:
    print(col)

학교종류명
설립구분
표준학교코드
학교명
영문학교명
관할조직명
도로명우편번호
도로명주소
도로명상세주소
전화번호
홈페이지주소
팩스번호
남녀공학구분명
고등학교구분명
산업체특별학급존재여부
고등학교일반실업구분명
특수목적고등학교계열명
입시전후기구분명
주야구분명
설립일자
개교기념일
시도교육청코드
시도교육청명
소재지명
주야과정
계열명
학과명
적재일시

In [5]:
df_school = df[['학교명','도로명주소','도로명상세주소']]

In [6]:
df_school

                    학교명                  도로명주소             도로명상세주소
0               선화예술중학교     서울특별시 광진구 천호대로 664    / 선화예술중고등학교 (능동)
1              서울숭신초등학교      서울특별시 성동구 마장로 161             (하왕십리동)
2                 행당중학교     서울특별시 성동구 왕십리로 189         (행당동/행당중학교)
3        한양대학교사범대학부속중학교       서울특별시 성동구 마조로 42  (사근동/한양사대부속중?고등학교)
4                 자양중학교    서울특별시 광진구 뚝섬로41길 33       (자양동/서울자양중학교)
...                 ...                    ...                 ...
3852           국립국악고등학교    서울특별시 강남구 개포로22길 65   / (개포동/ 국립국악고등학교)
3853             한국우진학교  서울특별시 마포구 월드컵북로38길 21       / 한국우진학교 (중동)
3854              서울농학교     서울특별시 종로구 필운대로 103               (신교동)
3855              서울맹학교      서울특별시 종로구 필운대로 97               (신교동)
3856  경기기계공업고등학교부설공동실습소      서울특별시 노원구 공릉로 264    (하계동/경기기계공업고등학교)

[3857 rows x 3 columns]

In [7]:
df_school.rename(columns={'도로명주소':'구명'}, inplace=True)
df_school.rename(columns={'도로명상세주소':'동명'}, inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [8]:
df_school

                    학교명                     구명                  동명
0               선화예술중학교     서울특별시 광진구 천호대로 664    / 선화예술중고등학교 (능동)
1              서울숭신초등학교      서울특별시 성동구 마장로 161             (하왕십리동)
2                 행당중학교     서울특별시 성동구 왕십리로 189         (행당동/행당중학교)
3        한양대학교사범대학부속중학교       서울특별시 성동구 마조로 42  (사근동/한양사대부속중?고등학교)
4                 자양중학교    서울특별시 광진구 뚝섬로41길 33       (자양동/서울자양중학교)
...                 ...                    ...                 ...
3852           국립국악고등학교    서울특별시 강남구 개포로22길 65   / (개포동/ 국립국악고등학교)
3853             한국우진학교  서울특별시 마포구 월드컵북로38길 21       / 한국우진학교 (중동)
3854              서울농학교     서울특별시 종로구 필운대로 103               (신교동)
3855              서울맹학교      서울특별시 종로구 필운대로 97               (신교동)
3856  경기기계공업고등학교부설공동실습소      서울특별시 노원구 공릉로 264    (하계동/경기기계공업고등학교)

[3857 rows x 3 columns]

In [9]:
df_gu = df_school['구명'].str.findall('\w+구')

In [10]:
df_gu

0       [광진구]
1       [성동구]
2       [성동구]
3       [성동구]
4       [광진구]
        ...
3852    [강남구]
3853    [마포구]
3854    [종로구]
3855    [종로구]
3856    [노원구]
Name: 구명, Length: 3857, dtype: object

In [11]:
df_school['구명'] = df_gu

<ipython-input-11-586ea134eada>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_school['구명'] = df_gu

In [13]:
df_Dong = df_school['동명'].str.findall('\w+동')

In [14]:
df_Dong

0          [능동]
1       [하왕십리동]
2         [행당동]
3         [사근동]
4         [자양동]
         ...
3852      [개포동]
3853       [중동]
3854      [신교동]
3855      [신교동]
3856      [하계동]
Name: 동명, Length: 3857, dtype: object

In [15]:
df_school['동명'] = df_Dong

<ipython-input-15-295ba2708356>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_school['동명'] = df_Dong

In [16]:
df_school

                    학교명     구명       동명
0               선화예술중학교  [광진구]     [능동]
1              서울숭신초등학교  [성동구]  [하왕십리동]
2                 행당중학교  [성동구]    [행당동]
3        한양대학교사범대학부속중학교  [성동구]    [사근동]
4                 자양중학교  [광진구]    [자양동]
...                 ...    ...      ...
3852           국립국악고등학교  [강남구]    [개포동]
3853             한국우진학교  [마포구]     [중동]
3854              서울농학교  [종로구]    [신교동]
3855              서울맹학교  [종로구]    [신교동]
3856  경기기계공업고등학교부설공동실습소  [노원구]    [하계동]

[3857 rows x 3 columns]

In [17]:
df_element = df_school.loc[df_school['학교명'].str.contains("초등학교")]

In [18]:
df_element

                   학교명      구명       동명
1             서울숭신초등학교   [성동구]  [하왕십리동]
25              한양초등학교   [성동구]    [사근동]
26              세종초등학교   [광진구]    [군자동]
27              성동초등학교   [광진구]    [자양동]
28            서울화양초등학교   [광진구]    [화양동]
...                ...     ...      ...
1002         서울답십리초등학교  [동대문구]   [답십리동]
1003          서울군자초등학교  [동대문구]    [장안동]
1004            금성초등학교   [중랑구]    [신내동]
1005            경희초등학교  [동대문구]    [회기동]
1421  학력인정 한림초등학교(4년제)   [송파구]    [장지동]

[611 rows x 3 columns]

In [19]:
df_element.rename(columns={'학교명':'초등학교명'}, inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [20]:
df_element

                 초등학교명      구명       동명
1             서울숭신초등학교   [성동구]  [하왕십리동]
25              한양초등학교   [성동구]    [사근동]
26              세종초등학교   [광진구]    [군자동]
27              성동초등학교   [광진구]    [자양동]
28            서울화양초등학교   [광진구]    [화양동]
...                ...     ...      ...
1002         서울답십리초등학교  [동대문구]   [답십리동]
1003          서울군자초등학교  [동대문구]    [장안동]
1004            금성초등학교   [중랑구]    [신내동]
1005            경희초등학교  [동대문구]    [회기동]
1421  학력인정 한림초등학교(4년제)   [송파구]    [장지동]

[611 rows x 3 columns]

In [21]:
df_element2 = df_element['구명']

In [22]:
type(df_element2[1])

list

In [23]:
# 인덱스 초기화
df3 =df_element.reset_index(level=None, drop=False)

In [24]:
df3

     index             초등학교명      구명       동명
0        1          서울숭신초등학교   [성동구]  [하왕십리동]
1       25            한양초등학교   [성동구]    [사근동]
2       26            세종초등학교   [광진구]    [군자동]
3       27            성동초등학교   [광진구]    [자양동]
4       28          서울화양초등학교   [광진구]    [화양동]
..     ...               ...     ...      ...
606   1002         서울답십리초등학교  [동대문구]   [답십리동]
607   1003          서울군자초등학교  [동대문구]    [장안동]
608   1004            금성초등학교   [중랑구]    [신내동]
609   1005            경희초등학교  [동대문구]    [회기동]
610   1421  학력인정 한림초등학교(4년제)   [송파구]    [장지동]

[611 rows x 4 columns]

In [25]:
for col in df3:
    print(col)

index
초등학교명
구명
동명

In [26]:
df3.drop(['index'], axis=1, inplace=True)

In [28]:
# CSV 파일로 저장하기

# df3.to_csv('element.csv', mode='a', header=True, encoding='cp949')

#

In [29]:
df3

                초등학교명      구명       동명
0            서울숭신초등학교   [성동구]  [하왕십리동]
1              한양초등학교   [성동구]    [사근동]
2              세종초등학교   [광진구]    [군자동]
3              성동초등학교   [광진구]    [자양동]
4            서울화양초등학교   [광진구]    [화양동]
..                ...     ...      ...
606         서울답십리초등학교  [동대문구]   [답십리동]
607          서울군자초등학교  [동대문구]    [장안동]
608            금성초등학교   [중랑구]    [신내동]
609            경희초등학교  [동대문구]    [회기동]
610  학력인정 한림초등학교(4년제)   [송파구]    [장지동]

[611 rows x 3 columns]

In [30]:
print(df3)

                초등학교명      구명       동명
0            서울숭신초등학교   [성동구]  [하왕십리동]
1              한양초등학교   [성동구]    [사근동]
2              세종초등학교   [광진구]    [군자동]
3              성동초등학교   [광진구]    [자양동]
4            서울화양초등학교   [광진구]    [화양동]
..                ...     ...      ...
606         서울답십리초등학교  [동대문구]   [답십리동]
607          서울군자초등학교  [동대문구]    [장안동]
608            금성초등학교   [중랑구]    [신내동]
609            경희초등학교  [동대문구]    [회기동]
610  학력인정 한림초등학교(4년제)   [송파구]    [장지동]

[611 rows x 3 columns]

In [56]:
df4 = df3['구명']

In [57]:
type(df4)

pandas.core.series.Series

In [58]:
# df4 = df3.groupby('구명').mean()

In [78]:
df4 = df3['구명']

In [77]:
df5 = df4

In [61]:
# df5[0] = '성동구'

In [62]:
# type(df5[0])

str

In [81]:
for a in df4:
    string=''.join(a)
    print(string)

성동구
성동구
광진구
광진구
광진구
성동구
성동구
광진구
광진구
광진구
광진구
성동구
광진구
성동구
광진구
성동구
성동구
광진구
광진구
광진구
광진구
성동구
광진구
성동구
성동구
성동구
성동구
성동구
광진구
광진구
성동구
성동구
성동구
성동구
광진구
광진구
광진구
광진구
광진구
성동구
성동구
성동구
광진구
동작구
동작구
동작구
관악구
관악구
관악구
관악구
동작구
관악구
관악구
동작구
동작구
관악구
관악구
동작구
관악구
관악구
동작구
동작구
동작구
동작구
동작구
관악구
관악구
관악구
관악구
동작구
동작구
관악구
동작구
동작구
동작구
관악구
동작구
동작구
동작구
관악구
관악구
관악구
관악구
관악구
관악구
동작구
강동구
강동구
송파구
강동구
송파구
강동구
송파구
송파구
송파구
송파구
강동구
강동구
강동구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
강동구
송파구
송파구
송파구
송파구
송파구
강동구
강동구
송파구
송파구
송파구
송파구
송파구
강동구
강동구
강동구
강동구
송파구
강동구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
강동구
강동구
강동구
강동구
송파구
강동구
강동구
송파구
강동구
강동구
강동구
강동구
송파구
송파구
송파구
강동구
강동구
강동구
강동구
송파구
송파구
송파구
송파구
성북구
강북구
성북구
성북구
성북구
성북구
강북구
성북구
성북구
성북구
성북구
성북구
성북구
성북구
성북구
강북구
강북구
성북구
강북구
강북구
성북구
성북구
성북구
성북구
성북구
강북구
강북구
강북구
강북구
성북구
성북구
성북구
강북구
성북구
강북구
강북구
강북구
성북구
성북구
성북구
성북구
성북구
성북구
강남구
강남구
서초구
강남구
서초구
강남구
강남구
강남구압구
서초구
강남구
서초구
서초구
서초구
서초구
강남구
강남구
강남구
강남구
강남구
서초구
강남구
서초구
강남구압구
서초구
서초구
강남구압구
강남구
서초구
서초구
서초구
서초구
서초구
강남구
강남구
서초구
서초구
서초구
서초구
서초구
서초구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
서초구
서초구
강서구
양천구
강서구
강서구
강서구
강서구
양천구
양천구
강서구
양천구
양천구
양천구
강서구
강서구
양천구
강서구
강서구
강서구
양천구
강서구
양천구
양천구
양천구
양천구
양천구
강서구
강서구
양천구
양천구
양천구
양천구
양천구
강서구
양천구
강서구
강서구
강서구
양천구
강서구
강서구
강서구
강서구
양천구
양천구
양천구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
양천구
강서구
강서구
양천구
양천구
강서구
양천구
양천구
양천구
양천구
강서구
강서구
종로구
종로구
용산구
중구
중구청구
용산구
종로구
종로구
용산구
용산구
중구
용산구
종로구
중구
종로구
종로구
중구청구
용산구
용산구
용산구
용산구
용산구
중구
종로구
용산구
용산구
중구
용산구
종로구
종로구
종로구
중구
용산구
중구
용산구
종로구
중구
종로구
중구
중구
노원구
도봉구
노원구
노원구
노원구
노원구
노원구
도봉구
노원구
도봉구
도봉구
도봉구
도봉구
도봉구
도봉구
노원구
노원구
노원구
노원구
도봉구
노원구
도봉구
노원구
노원구
노원구
노원구
노원구
도봉구
노원구
노원구
도봉구
도봉구
도봉구
도봉구
노원구
도봉구
노원구
도봉구
노원구
노원구
노원구
노원구
노원구
노원구
노원구
노원구
노원구
노원구
노원구
도봉구
도봉구
노원구
도봉구
노원구
노원구
도봉구
노원구
노원구
노원구
노원구
노원구
노원구
도봉구
노원구
도봉구
구로구
구로구
금천구
구로구
영등포구
구로구
금천구
금천구
영등포구
영등포구
구로구
구로구
구로구
구로구
영등포구
구로구
영등포구
영등포구
구로구
영등포구
영등포구
영등포구
영등포구
금천구
영등포구
금천구
금천구
영등포구
구로구
구로구
영등포구
구로구
금천구
구로구
영등포구
금천구
구로구
금천구
금천구
영등포구
금천구
구로구
금천구
구로구
금천구
영등포구
영등포구
구로구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
금천구
금천구
금천구
구로구
구로구
구로구
구로구
구로구
구로구
구로구
구로구
구로구
금천구
금천구
은평구
서대문구
은평구
마포구
은평구
마포구
은평구
서대문구
서대문구
은평구
은평구
은평구
서대문구
서대문구
서대문구
마포구
마포구
서대문구
은평구
은평구
마포구
서대문구
은평구
은평구
은평구
은평구
마포구
마포구
서대문구
은평구
은평구
은평구
은평구
서대문구
은평구
서대문구
마포구
마포구
은평구
마포구
은평구
은평구
마포구
마포구
마포구
마포구
은평구
마포구
마포구
마포구
마포구
은평구
은평구
은평구
서대문구
서대문구
서대문구
마포구
마포구
마포구
은평구
은평구
서대문구
은평구
서대문구
은평구
은평구
마포구
서대문구
은평구
서대문구
서대문구
중랑구
동대문구
동대문구
동대문구
동대문구
동대문구
동대문구
동대문구
중랑구
중랑구
중랑구
중랑구
중랑구
동대문구
동대문구
동대문구
동대문구
동대문구
동대문구
중랑구
동대문구
동대문구
중랑구
중랑구
동대문구
중랑구
중랑구
중랑구
동대문구
중랑구
중랑구
중랑구
중랑구
중랑구
중랑구
중랑구
중랑구
중랑구
중랑구
동대문구
동대문구
동대문구
중랑구
동대문구
송파구

In [74]:
df6

'성동구성동구성동구광진구광진구광진구성동구성동구광진구광진구광진구광진구성동구광진구성동구광진구성동구성동구광진구광진구광진구광진구성동구광진구성동구성동구성동구성동구성동구광진구광진구성동구성동구성동구성동구광진구광진구광진구광진구광진구성동구성동구성동구광진구동작구동작구동작구관악구관악구관악구관악구동작구관악구관악구동작구동작구관악구관악구동작구관악구관악구동작구동작구동작구동작구동작구관악구관악구관악구관악구동작구동작구관악구동작구동작구동작구관악구동작구동작구동작구관악구관악구관악구관악구관악구관악구동작구강동구강동구송파구강동구송파구강동구송파구송파구송파구송파구강동구강동구강동구송파구송파구송파구송파구송파구송파구송파구강동구송파구송파구송파구송파구송파구강동구강동구송파구송파구송파구송파구송파구강동구강동구강동구강동구송파구강동구송파구송파구송파구송파구송파구송파구송파구강동구강동구강동구강동구송파구강동구강동구송파구강동구강동구강동구강동구송파구송파구송파구강동구강동구강동구강동구송파구송파구송파구송파구성북구강북구성북구성북구성북구성북구강북구성북구성북구성북구성북구성북구성북구성북구성북구강북구강북구성북구강북구강북구성북구성북구성북구성북구성북구강북구강북구강북구강북구성북구성북구성북구강북구성북구강북구강북구강북구성북구성북구성북구성북구성북구성북구강남구강남구서초구강남구서초구강남구강남구강남구압구서초구강남구서초구서초구서초구서초구강남구강남구강남구강남구강남구서초구강남구서초구강남구압구서초구서초구강남구압구강남구서초구서초구서초구서초구서초구강남구강남구서초구서초구서초구서초구서초구서초구강남구강남구강남구강남구강남구강남구강남구강남구강남구강남구강남구강남구강남구강남구강남구서초구서초구강서구양천구강서구강서구강서구강서구양천구양천구강서구양천구양천구양천구강서구강서구양천구강서구강서구강서구양천구강서구양천구양천구양천구양천구양천구강서구강서구양천구양천구양천구양천구양천구강서구양천구강서구강서구강서구양천구강서구강서구강서구강서구양천구양천구양천구강서구강서구강서구강서구강서구강서구강서구강서구양천구강서구강서구양천구양천구강서구양천구양천구양천구양천구강서구강서구종로구종로구용산구중구중구청구용산구종로구종로구용산구용산구중구용산구종로구중구종로구종로구중구청구용산구용산구용산구용산구용산구중구종로구용산구용산구중구용산구종로구종로구종로구중구용산구중구용산구종로구중구종로구중구중구노원구도봉구노원구노원구노원구노원구노원구도봉구노원구도봉구도봉구도봉구도봉구도봉구도봉구노원구노원구노원구노원구도봉구노원구도봉구노원구노원구노원구노원구노원구도봉구노원구노원구도봉구도봉구도봉구도봉구노원구도봉구노원구도봉구노원구노원구노원구노원구노원구노원구노원구노원구노원구노원구노원구도봉구도봉구노원구도봉구노원구노원구도봉구노원구노원구노원구노원구노원구노원구도봉구노원구도봉구구로구구로구금천구구로구영등포구구로구금천구금천구영등포구영등포구구로구구로구구로구구로구영등포구구로구영등포구영등포구구로구영등포구영등포구영등포구영등포구금천구영등포구금천구금천구영등포구구로구구로구영등포구구로구금천구구로구영등포구금천구구로구금천구금천구영등포구금천구구로구금천구구로구금천구영등포구영등포구구로구영등포구영등포구영등포구영등포구영등포구영등포구영등포구금천구금천구금천구구로구구로구구로구구로구구로구구로구구로구구로구구로구금천구금천구은평구서대문구은평구마포구은평구마포구은평구서대문구서대문구은평구은평구은평구서대문구서대문구서대문구마포구마포구서대문구은평구은평구마포구서대문구은평구은평구은평구은평구마포구마포구서대문구은평구은평구은평구은평구서대문구은평구서대문구마포구마포구은평구마포구은평구은평구마포구마포구마포구마포구은평구마포구마포구마포구마포구은평구은평구은평구서대문구서대문구서대문구마포구마포구마포구은평구은평구서대문구은평구서대문구은평구은평구마포구서대문구은평구서대문구서대문구중랑구동대문구동대문구동대문구동대문구동대문구동대문구동대문구중랑구중랑구중랑구중랑구중랑구동대문구동대문구동대문구동대문구동대문구동대문구중랑구동대문구동대문구중랑구중랑구동대문구중랑구중랑구중랑구동대문구중랑구중랑구중랑구중랑구중랑구중랑구중랑구중랑구중랑구중랑구동대문구동대문구동대문구중랑구동대문구송파구성동구'